title: "Sprint 2: Ethical Data."
email: 'gladishd@carleton.edu'
description: "As technology accelerates ahead, it's important to think about the ethical side of technology, especially when working with huge amounts of users data."
url: "https://gladishd.github.io/ethical-data"
twitter_username: 'gladishd'
github_username: 'gladishd'
medium_username: 'blog.gladishd.com'
markdown: kramdown
plugins:
  - jekyll-paginate-v2
pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2
  extension: html
  indexpage: 'index'
footer_text: '© 2021 Dean Gladish, Marco Chan, Prashi Doval'
admin_name: 'Dean Gladish'
google_analytics: "UA-9999999-99"
enable_contact: false
enable_nav: true
nav_item:
  - { url: '/', text: 'Home' }
  - { url: '/about', text: 'About' }
